package com.musync.sync

object SocketEvents {
    const val JOIN_ROOM = "join_room"
    const val LEAVE_ROOM = "leave_room"
    const val END_SESSION = "end_session"
    const val ROOM_CLOSED = "ROOM_CLOSED"
    const val SYNC_HEARTBEAT = "SYNC_HEARTBEAT"
    const val QUEUE_UPDATED = "QUEUE_UPDATED"
    const val PLAY = "PLAY"
    const val PAUSE = "PAUSE"
    const val SEEK = "SEEK"
    const val PEER_JOINED = "peer_joined"
    const val PEER_LEFT = "peer_left"
    const val CHAT_MESSAGE = "CHAT_MESSAGE"
    const val REACTION = "REACTION"
    const val TYPING = "TYPING"
    const val TRANSFER_HOST = "TRANSFER_HOST"
    const val HOST_TRANSFERRED = "HOST_TRANSFERRED"
    const val SET_DEMOCRATIC_MODE = "SET_DEMOCRATIC_MODE"
    const val DEMOCRATIC_MODE_CHANGED = "DEMOCRATIC_MODE_CHANGED"
    const val SET_AUTO_APPROVE_QUEUE = "SET_AUTO_APPROVE_QUEUE"
    const val AUTO_APPROVE_QUEUE_CHANGED = "AUTO_APPROVE_QUEUE_CHANGED"
    const val REQUEST_QUEUE_ADD = "REQUEST_QUEUE_ADD"
    const val QUEUE_ADD_REQUEST = "QUEUE_ADD_REQUEST"
    const val APPROVE_QUEUE_ADD = "APPROVE_QUEUE_ADD"
}
